host: "127.0.0.1" # webhook地址，如果启用ws，一般为0.0.0.0
port: 9000 # webhook监听端口
ws: false # 是否启用ws
ws_token: "" # ws连接认证token
download_url: "http://ip:port/"

FileType: [ ".cover.jpg", ".xml", ".flv" ] # 文件类型

local:
  enable: true
  RecordPath: "/opt/RecordFiles" # 本地录制存储路径, 末尾需加“/”
  OutputPath: "/opt/archive/" # 录播文件保存路径

timer:
  time: 300 # 倒计时时间

pcs:
  Enable: true
  ClientId: "" # 百度网盘开放平台应用AppKey
  SecretKey: "" # 百度网盘开放平台应用SecretKey
  AccessToken: "" # 百度网盘access_token，如果为空将尝试自动获取
  RedirectUrl: "oob" # 百度网盘开放平台回调地址
  PcsPath: "/bili_rec_monitor/" # 百度云保存路径
